-- PostgreSQL initialization for the intentionally vulnerable interview lab.
-- The official image creates the database and user from POSTGRES_* variables
-- before executing this file.

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    is_admin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS posts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content TEXT,
    author_id INTEGER REFERENCES users(id),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INTEGER REFERENCES posts(id),
    author VARCHAR(50),
    content TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (id, username, password, email, is_admin) VALUES
    (1, 'admin', 'admin123', 'admin@example.com', TRUE),
    (2, 'user1', 'password123', 'user1@example.com', FALSE),
    (3, 'user2', 'password456', 'user2@example.com', FALSE),
    (4, 'testuser', 'testpass', 'test@example.com', FALSE),
    (5, 'john_doe', 'john123', 'john@example.com', FALSE),
    (6, 'jane_smith', 'jane456', 'jane@example.com', FALSE),
    (7, 'bob_wilson', 'bob789', 'bob@example.com', FALSE),
    (8, 'sensitive_user', 'secret_password', 'sensitive@example.com', FALSE),
    (9, 'admin_backup', 'backup_admin_pass', 'backup@example.com', TRUE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO posts (id, title, content, author_id) VALUES
    (1, 'Welcome to the Vulnerable App', 'This is an intentionally vulnerable application for security testing.', 1),
    (2, 'SQL Injection Test Post', 'This post is designed for testing SQL injection vulnerabilities.', 1),
    (3, 'XSS Testing Content', 'This post contains content for testing cross-site scripting vulnerabilities.', 1),
    (4, 'Security Best Practices', 'Always validate input, use parameterized queries, and implement proper authentication.', 2),
    (5, 'Database Security', 'Use least privilege, encrypt sensitive data, and monitor suspicious activity.', 2),
    (6, 'API Security', 'API security is important as applications increasingly rely on APIs.', 5),
    (7, 'Authentication Methods', 'Authentication methods have different security implications.', 6),
    (8, 'Session Management', 'Proper session management is crucial for application security.', 7),
    (9, 'Internal Document', 'This internal document should not be accessible to regular users.', 1),
    (10, 'Confidential Information', 'This post contains confidential information that should be protected.', 1),
    (11, 'System Configuration', 'Database connection string: postgresql://admin:password@localhost:5432/db', 1),
    (12, 'Load Test Post 1', 'This is a load test post for performance testing.', 1),
    (13, 'Load Test Post 2', 'Another load test post for performance testing.', 1),
    (14, 'Load Test Post 3', 'Third load test post for performance testing.', 1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO comments (id, post_id, author, content) VALUES
    (1, 1, 'user1', 'Great post! This is very informative.'),
    (2, 1, 'user2', 'Thanks for sharing this information.'),
    (3, 2, 'user1', 'This is a test comment for SQL injection testing.'),
    (4, 2, 'user2', 'Another comment to test the system.'),
    (5, 3, 'user1', 'XSS test: <script>alert("test")</script>'),
    (6, 3, 'user2', 'XSS test: <img src=x onerror=alert("XSS")>'),
    (7, 4, 'user1', 'Security is very important in web applications.'),
    (8, 4, 'user2', 'Proper security measures are essential.'),
    (9, 5, 'user1', 'Database security is often overlooked but critical.'),
    (10, 5, 'user2', 'Monitoring and logging are key components of database security.'),
    (11, 6, 'john_doe', 'API security is crucial in modern applications.'),
    (12, 6, 'jane_smith', 'Great point about API security considerations.'),
    (13, 7, 'bob_wilson', 'Authentication is the foundation of application security.'),
    (14, 7, 'john_doe', 'Multi-factor authentication adds another security layer.'),
    (15, 8, 'jane_smith', 'Session management is often implemented incorrectly.'),
    (16, 8, 'bob_wilson', 'Session timeout and invalidation are important.'),
    (17, 12, 'user1', 'Load test comment 1'),
    (18, 12, 'user2', 'Load test comment 2'),
    (19, 13, 'user1', 'Load test comment 3'),
    (20, 13, 'user2', 'Load test comment 4'),
    (21, 14, 'user1', 'Load test comment 5'),
    (22, 14, 'user2', 'Load test comment 6')
ON CONFLICT (id) DO NOTHING;

CREATE OR REPLACE VIEW user_posts AS
SELECT u.username, p.title, p.content, p.created_at
FROM users AS u
JOIN posts AS p ON p.author_id = u.id;

CREATE INDEX IF NOT EXISTS idx_posts_author ON posts(author_id);
CREATE INDEX IF NOT EXISTS idx_comments_post ON comments(post_id);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);

SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE(MAX(id), 1), TRUE) FROM users;
SELECT setval(pg_get_serial_sequence('posts', 'id'), COALESCE(MAX(id), 1), TRUE) FROM posts;
SELECT setval(pg_get_serial_sequence('comments', 'id'), COALESCE(MAX(id), 1), TRUE) FROM comments;

SELECT 'Database initialization completed successfully!' AS status;

