-- PostgreSQL initialization for the intentionally vulnerable training app.
-- Run while connected to vulnerable_app as its owner.

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    is_admin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS posts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content TEXT,
    author_id INTEGER REFERENCES users(id),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INTEGER REFERENCES posts(id),
    author VARCHAR(50),
    content TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

TRUNCATE TABLE comments, posts, users RESTART IDENTITY CASCADE;

INSERT INTO users (username, password, email, is_admin) VALUES
('admin', 'admin123', 'admin@example.com', TRUE),
('user1', 'password123', 'user1@example.com', FALSE),
('user2', 'password456', 'user2@example.com', FALSE),
('testuser', 'testpass', 'test@example.com', FALSE),
('john_doe', 'john123', 'john@example.com', FALSE),
('jane_smith', 'jane456', 'jane@example.com', FALSE),
('bob_wilson', 'bob789', 'bob@example.com', FALSE),
('sensitive_user', 'secret_password', 'sensitive@example.com', FALSE),
('admin_backup', 'backup_admin_pass', 'backup@example.com', TRUE);

INSERT INTO posts (title, content, author_id) VALUES
('Welcome to the Vulnerable App', 'An intentionally vulnerable application for authorized security testing.', 1),
('SQL Injection Test Post', 'Use this record for controlled SQL injection testing.', 1),
('XSS Testing Content', 'Use the comment system for controlled XSS testing.', 1),
('Security Best Practices', 'Validate input, parameterize queries, and enforce authorization.', 2),
('Database Security', 'Use least privilege, encryption, and monitoring.', 2),
('API Security', 'APIs require authentication, authorization, validation, and observability.', 5),
('Authentication Methods', 'Authentication mechanisms have different security trade-offs.', 6),
('Session Management', 'Session timeout and invalidation must be designed carefully.', 7),
('Internal Document', 'Training-only internal content.', 1),
('Confidential Information', 'Training-only confidential content.', 1),
('System Configuration', 'Training example connection string: postgresql://example:redacted@db:5432/example', 1);

INSERT INTO comments (post_id, author, content) VALUES
(1, 'user1', 'Great post!'),
(1, 'user2', 'Thanks for sharing.'),
(2, 'user1', 'SQL injection test comment.'),
(3, 'user1', '<script>alert("training-xss")</script>'),
(3, 'user2', '<img src=x onerror=alert("training-xss")>'),
(4, 'user1', 'Security controls should be tested continuously.');

CREATE OR REPLACE VIEW user_posts AS
SELECT u.username, p.title, p.content, p.created_at
FROM users u JOIN posts p ON u.id = p.author_id;

CREATE OR REPLACE FUNCTION get_user_posts(requested_user_id INTEGER)
RETURNS TABLE(title VARCHAR, content TEXT, created_at TIMESTAMPTZ)
LANGUAGE SQL
AS $$
  SELECT p.title, p.content, p.created_at
  FROM posts p WHERE p.author_id = requested_user_id;
$$;
