apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - service-account.yaml
  - deployment.yaml
  - service.yaml
  - network-policies.yaml
  - ingress.yaml
images:
  - name: vulnerable-flask
    newName: 854481201284.dkr.ecr.us-west-2.amazonaws.com/eks-interview-lab/vulnerable-app
    digest: sha256:55d7a4241c3aadc90a74089953c498b33b401195dc5bb94ef66ad7acb2227adc
