apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - service-account.yaml
  - deployment.yaml
  - service.yaml
  - network-policies.yaml
  - ingress.yaml
images:
  - name: vulnerable-flask
    newName: 854481201284.dkr.ecr.us-west-2.amazonaws.com/eks-interview-lab/vulnerable-app
    digest: sha256:ecfa671ea77b6cc809fd51f2a6f436886efd35214ef85946a545375b8f837e9a
