apiVersion: v1
kind: Service
metadata:
  name: vulnerable-app
  namespace: vulnerable-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vulnerable-app
  ports:
    - name: http
      port: 80
      targetPort: http
