apiVersion: v1
kind: Secret
metadata:
  name: vulnerable-app-secrets
  namespace: vulnerable-app
type: Opaque
stringData:
  DB_PASSWORD: REPLACE_ME
  FLASK_SECRET_KEY: REPLACE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: database
type: Opaque
stringData:
  postgres-password: REPLACE_ME
  password: REPLACE_ME
